version: "3.8"
services:
  dev:
    init: true
    build:
      context: ../
      dockerfile: .devcontainer/dev.dockerfile
      args:
        HADOLINT_URL: ${HADOLINT_URL}
    hostname: builder
    # ホストからDBeaver用にポートを公開
    ports:
      - target: 5432
        published: 5432
    volumes:
      - type: bind
        source: ../
        target: /workspace
    stdin_open: true
    tty: true
