#ifndef INCLUDED_STD_EXT_VARIANT_RECORD_RECORD_HPP
#define INCLUDED_STD_EXT_VARIANT_RECORD_RECORD_HPP
#include "operator_io.hpp"
#include "type.hpp"
#endif // INCLUDED_STD_EXT_VARIANT_RECORD_RECORD_HPP
