services:
  db:
    build:
      context: ./dockerfiles
      dockerfile: db.Dockerfile
    restart: always
    hostname: db_server
    networks:
      - db_nw
    volumes:
      - type: bind
        source: initdb
        target: /docker-entrypoint-initdb.d
    # ホストからDBeaver用にポートを公開
    ports:
      - target: 5432
        published: 5432
    stdin_open: false
    tty: false

networks:
  db_nw:
    external: false
